### ISSUE TITLE
train guide

### ISSUE THREAD

**Issue by vinnitu** [HasnainRaz/Skin-Segmentation-TensorFlow#1]
Hello! 

Can you show how you prepare data to train?

**Comment by HasnainRaz** [comment]
If you are asking where about the origins of the dataset, it's a private dataset, with people's pictures and binary masks of skin marked pixel wise.
If you are asking about how to load the data for training, the utility.py does that, you can refer to my input pipeline for segmentation, the how-to guide is also shown on the link:
https://github.com/HasnainRaz/Tensorflow-input-pipeline

**Comment by vinnitu** [comment]
I am asking about dataset, but if your is private maybe you can add one image and one mask for example to training dir?

**Comment by liuhongbo830117** [comment]
Hi 
I would like to test your code. I have some training images and corresponding mask, but the code still needs the "val_image" and "val_mask". I am not sure how they look like and how to obtain them based what I currently have.  Thanks.

**Comment by HasnainRaz** [comment]
@vinnitu I can't really include an image as an example because of data privacy issues, but you the mask is supposed to be an image where white pixels denote class 1, and black pixels denote class 0. So it would simply be a black and white image, with white pixels where the skin is in the image. something like this: http://campar.in.tum.de/Students/IdpSkinSegmentation
The first two images show the image and mask pair.

@liuhongbo830117 val_images and masks are a subset of your training images and masks, these images are what will be used to run evaluation during training to serve as a measure of how good the model is getting on unseen images. so simply move a few images and masks from the training folder into the val folders.

**Comment by imane0897** [comment]
Hey guys, for those new to TensorFlow, I [forked](https://github.com/imane0897/Skin-Segmentation-TensorFlow) this repo and trained model based on [this](http://cs-chan.com/downloads_skin_dataset.html) data set. Training results and test results are also provided, so there is no need to run on your own machine (really took me a loooooong time)
