### ISSUE TITLE
hair detect

### ISSUE THREAD

**Issue by vinnitu** [HasnainRaz/Skin-Segmentation-TensorFlow#4]
I have prepared (not big) data set with hair masks by analogy with skin

Tell me please does such a idea make any sense whatsoever?

**Comment by HasnainRaz** [comment]
The idea seems okay, although I think you won't be able to get very good accuracy since hair strands can be notoriously difficult to segment, information being lost in downsampling etc. I would recommend you try a smaller version of the 100 layer tiramisu to use low level features, or incorporate deep image matting techniques into the network.
